name: MacOS - Build GUI Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: macos-10.15 
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    # macos-10.15 already has python 3.7.8.

    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      # pip3 might not refer to python3.7's pip. That's okay because pipenv install/run will use
      # python3.7 for its virtual environment. This is safer than writing python3.7 -m pip because
      # python3.7 in macos image is sometimes installed as python3.7m and not python3.7
      run: |
        pip3 install pipenv
    - name: Install geos (Shapely Dependency)
      run: |
        brew install geos
    - name: Install dependencies via pipenv
      # Sometimes macOS 10.15 pipenv thinks it's already running in a virtual environment
      # when it is actually not. PIPENV_IGNORE_VIRTUALENVS=1 forces pipenv to create a new
      # virtual environment anyway.
      # Shapely has bugs that occurs when it cannot link with the geos package properly.
      # Forcing pip to install this with no binary PIP_NO_BINARY="shapely" fixes this problem.
      run: |
        export PIPENV_IGNORE_VIRTUALENVS=1
        pipenv install --dev
    - name: Create macos app
      run: |
        pipenv run pyinstaller pyinstaller_spec/empress_gui_app.spec
    - name: Compress macos app
      # actions/upload-artifact@v2 cannot upload symlinks correctly
      # https://github.com/actions/upload-artifact/issues/92
      # This can be fixed by zipping the folder before uploading. By doing this, we end up
      # double-zipping the file, which is not optimal.
      run: |
        cd ./dist
        zip -r macos_empress_app.zip empress.app
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: macos_empress_app
        path: ./dist/macos_empress_app.zip
