name: Create empress graphical user interface app in macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: macos-10.15 
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    # macos-10.15 already has python 3.7.8, no need to install

    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        PIP_NO_BINARY="shapely" pipenv install --dev
    - name: Create MacOS app
      run: |
        pipenv run pyinstaller pyinstaller_spec/empress_gui_app.spec
    - name: Upload draw examples
      uses: actions/upload-artifact@v2
      with:
        name: macos_empress_app
        path: ./dist