name: Create empress graphical user interface app in macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: macos-10.15 
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    # macos-10.15 already has python 3.7.8, no need to install

    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: |
        pip3 install pipenv
    - name: Install geos (Shapely Dependency)
      run: |
        brew install geos
    - name: Install dependencies via pipenv
        PIP_NO_BINARY="shapely" python3 -m pipenv install --dev
    - name: Create macos app
      run: |
        pipenv run pyinstaller pyinstaller_spec/empress_gui_app.spec
    - name: Compress macos app
      run: |
        zip -r macos_empress_app.zip ./dist/empress.app
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: macos_empress_app
        path: ./macos_empress_app.zip
