# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Install dependencies and run empress

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev
    - name: [Not Run] Lint with flake8
      run: |
        # pipenv install flake8
        # stop the build if there are Python syntax errors or undefined names
        # pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run empress_cli help
      run: |
        pipenv run python empress_cli.py --help
    - name: Run cost region example in Readme.md
      run: |
        pipenv run python empress_cli.py -fn examples/heliconius.newick costscape -tl 0.5 -th 10 -dl 0.5 -dh 10 --outfile costscape-example-img.pdf --log
    - name: Run reconcile example in Readme.md
      run: |
        pipenv run python empress_cli.py -fn examples/heliconius.newick reconcile -d 4 -t 2 -l 0
    - name: Run distance pair histogram example in Readme.md
      run: |
        pipenv run python empress_cli.py -fn examples/heliconius.newick histogram --csv foo.csv --histogram bar.pdf --ynorm
    - name: Run cluster example in Readme.md
      run: |
        pipenv run python empress_cli.py -fn examples/heliconius.newick clumpr --median --nmprs 4 --support
