# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests and Draw Examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run unittests
      run: |
        pipenv run python -m unittest
    - name: Run cli readme examples
      run: |
        pipenv run python test/cli/run_readme_examples.py
    - name: Run cli integration test
      run: |
        pipenv run python test/cli/run_command_combinations.py 100
    - name: Run draw examples for empress wrapper
      run: |
        pipenv run python -m unittest discover --start-directory ./test/draw --pattern "draw_*.py"
    - name: Upload draw examples
      uses: actions/upload-artifact@v4
      with:
        name: draw_examples_output
        path: ./draw_examples_output
